### PR TITLE
More 1.28 bumps

### PR DESCRIPTION
**Pull request by oz123**
Some minor bumps.

I also removed the 1.27.x series ebuilds if there is already a 1.28.x version.

### CODE REVIEW

**Review by immolo — APPROVED** [review]
Good shout I meant to do it as I went but after a couple of hours I needed the break. :)

**Comment by immolo** [comment]
I'll likely drop 1.26 from here as well as I would like the process to be:

1.  bump to 1.28
2. merge to gentoo (closes most open bugs so needs linking)
3. switch to meson (I need to learn that so if you could do an example one to help as a guide I'll appreciate it)
4. merge meson
5. MATE should have released wayland-session-manager by this point so out of tree testing can happen.
6. merge wayland

if you have any better ideas though to help I'd love to hear them as my gentoo time is split between a few projects so you might have a clearer head than me on this :)

Thanks again <3

**Comment by oz123** [comment]
Meson is a good thing, but not all packages support it yet. I suggest we wait with it, because that will make things with the eclass easier.
Also, I don't use wayland - I don't see why yet - x still works ... so I can't help with testing that.
Removing 1.26 is good!

**Comment by immolo** [comment]
I'd like to do the wayland part for the challenge anyway, better to give
the user choice for their needs not our needs but I understand why you
wouldn't want to waste time on this :)

Gentoo have asked to start the update process, can you explain your idea
with the eclass so when I'm asked again I can explain why we decided to
hold off?

**Pull request merged**
